### ISSUE TITLE
Writing IndexRange_t on windows 64

### ISSUE THREAD

**Issue by xgarnaud** [pyCGNS/pyCGNS#8]
Dear all,

It seems MAP does not write IndexRange_t correctly when the array is of dtype int32
If I do the following:
pattern1 = [CGK.Zone_ts,CGK.ZoneBC_ts,CGK.BC_ts,CGK.IndexRange_ts]
for pth in CGU.getPathsByTypeOrNameList(zone,pattern1):
    n = CGU.getNodeByPath(zone,pth)
    n[1] = ((n[1]-1)/2 + 1)
I get an MT node in the cgns file, if I add .astype(np.int64) I get the correct value.

Best regards,

Xavier

**Comment by MicK7** [comment]
Hello,

I am not sure of the problem since I can't reproduce it.
On windows 64, I do get a correct int32 writing with your code if I put a astype(np.int32)
but I need to write this formula to get correct values:
n[1] = ((n[1]-1)//2 +1)
otherwise n[1] becomes a float64 type on my computer.

Best regards

Mickael
