### ISSUE TITLE
[PAT]cgnsutils.getPathsByTypeOrNameList interface seems inconsistent

### ISSUE THREAD

**Issue by picost** [pyCGNS/pyCGNS#87]
The interface of the  getPathsByTypeOrNameList function, according to doc, is to return a list of paths. 

However, in the cases when there is no match in the tree right from the beginning, the returned result is `None`, whereas when there exist a "partial" match, the result is an empty list.

An example is given here-under:

```
import CGNS.PAT.cgnskeywords as CGK
import CGNS.PAT.cgnslib as CGL
import CGNS.PAT.cgnsutils as CGU
import numpy as np

tree = CGL.newCGNSTree()
base = CGL.newCGNSBase(tree, 'BaseTest', 3, 3)
dim = np.array([[10],[2],[0]],dtype=np.int32)
zone = CGL.newZone(base, 'ZoneTest', dim)

res_normal = CGU.getPathsByTypeOrNameList(
        tree, [CGK.CGNSTree_ts, CGK.CGNSBase_ts])
assert(res_normal == ['/BaseTest'])

res_None = CGU.getPathsByTypeOrNameList(tree, ['Zaza'])
assert(res_None is None)

res_empty_list = CGU.getPathsByTypeOrNameList(
        tree, [CGK.CGNSTree_ts, 'Zaza'])
assert(res_empty_list == [])
```

As the main use of this function is to return a list of paths to be iterated, I would suggest to drop the `None` result and return an empty list instead to keep consistency among the returned result and avoid None-checking by the user before iterating on the result of the function. (But this may brake hypothetical code expecting None result...)

**Comment by MicK7** [comment]
First, None or empty list in the result can be tested in python through a
"if not result: " statement. So it is not a major issue right now.

Second, I agree that returning None or empty list is a random behavior that should be removed.
None makes sense since nothing is found but if we expect a match and need to iterate on result may be empty list would be a better choice.
